/**
 * generated by Xtext 2.25.0
 */
package self_checkout_experience.selfCheckoutExperience;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Add To Basket</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link self_checkout_experience.selfCheckoutExperience.AddToBasket#getItem <em>Item</em>}</li>
 * </ul>
 *
 * @see self_checkout_experience.selfCheckoutExperience.SelfCheckoutExperiencePackage#getAddToBasket()
 * @model
 * @generated
 */
public interface AddToBasket extends EObject
{
  /**
   * Returns the value of the '<em><b>Item</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Item</em>' reference.
   * @see #setItem(PickStatement)
   * @see self_checkout_experience.selfCheckoutExperience.SelfCheckoutExperiencePackage#getAddToBasket_Item()
   * @model
   * @generated
   */
  PickStatement getItem();

  /**
   * Sets the value of the '{@link self_checkout_experience.selfCheckoutExperience.AddToBasket#getItem <em>Item</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Item</em>' reference.
   * @see #getItem()
   * @generated
   */
  void setItem(PickStatement value);

} // AddToBasket
