/**
 * generated by Xtext 2.25.0
 */
package self_checkout_experience.selfCheckoutExperience;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Checkout</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link self_checkout_experience.selfCheckoutExperience.Checkout#getScan <em>Scan</em>}</li>
 *   <li>{@link self_checkout_experience.selfCheckoutExperience.Checkout#getPay <em>Pay</em>}</li>
 * </ul>
 *
 * @see self_checkout_experience.selfCheckoutExperience.SelfCheckoutExperiencePackage#getCheckout()
 * @model
 * @generated
 */
public interface Checkout extends EObject
{
  /**
   * Returns the value of the '<em><b>Scan</b></em>' containment reference list.
   * The list contents are of type {@link self_checkout_experience.selfCheckoutExperience.Scan}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scan</em>' containment reference list.
   * @see self_checkout_experience.selfCheckoutExperience.SelfCheckoutExperiencePackage#getCheckout_Scan()
   * @model containment="true"
   * @generated
   */
  EList<Scan> getScan();

  /**
   * Returns the value of the '<em><b>Pay</b></em>' attribute.
   * The literals are from the enumeration {@link self_checkout_experience.selfCheckoutExperience.Pay}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pay</em>' attribute.
   * @see self_checkout_experience.selfCheckoutExperience.Pay
   * @see #setPay(Pay)
   * @see self_checkout_experience.selfCheckoutExperience.SelfCheckoutExperiencePackage#getCheckout_Pay()
   * @model
   * @generated
   */
  Pay getPay();

  /**
   * Sets the value of the '{@link self_checkout_experience.selfCheckoutExperience.Checkout#getPay <em>Pay</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pay</em>' attribute.
   * @see self_checkout_experience.selfCheckoutExperience.Pay
   * @see #getPay()
   * @generated
   */
  void setPay(Pay value);

} // Checkout
