/**
 * generated by Xtext 2.25.0
 */
package self_checkout_experience.selfCheckoutExperience;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Complex Scan</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link self_checkout_experience.selfCheckoutExperience.ComplexScan#getStart <em>Start</em>}</li>
 *   <li>{@link self_checkout_experience.selfCheckoutExperience.ComplexScan#getNext <em>Next</em>}</li>
 * </ul>
 *
 * @see self_checkout_experience.selfCheckoutExperience.SelfCheckoutExperiencePackage#getComplexScan()
 * @model
 * @generated
 */
public interface ComplexScan extends ScanExpression
{
  /**
   * Returns the value of the '<em><b>Start</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start</em>' containment reference.
   * @see #setStart(Scan)
   * @see self_checkout_experience.selfCheckoutExperience.SelfCheckoutExperiencePackage#getComplexScan_Start()
   * @model containment="true"
   * @generated
   */
  Scan getStart();

  /**
   * Sets the value of the '{@link self_checkout_experience.selfCheckoutExperience.ComplexScan#getStart <em>Start</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start</em>' containment reference.
   * @see #getStart()
   * @generated
   */
  void setStart(Scan value);

  /**
   * Returns the value of the '<em><b>Next</b></em>' containment reference list.
   * The list contents are of type {@link self_checkout_experience.selfCheckoutExperience.AddToBag}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Next</em>' containment reference list.
   * @see self_checkout_experience.selfCheckoutExperience.SelfCheckoutExperiencePackage#getComplexScan_Next()
   * @model containment="true"
   * @generated
   */
  EList<AddToBag> getNext();

} // ComplexScan
