/**
 * generated by Xtext 2.25.0
 */
package self_checkout_experience.selfCheckoutExperience;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Repeat</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link self_checkout_experience.selfCheckoutExperience.Repeat#getCount <em>Count</em>}</li>
 *   <li>{@link self_checkout_experience.selfCheckoutExperience.Repeat#getStatements <em>Statements</em>}</li>
 * </ul>
 *
 * @see self_checkout_experience.selfCheckoutExperience.SelfCheckoutExperiencePackage#getRepeat()
 * @model
 * @generated
 */
public interface Repeat extends WalkStatement
{
  /**
   * Returns the value of the '<em><b>Count</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Count</em>' containment reference.
   * @see #setCount(IntExpression)
   * @see self_checkout_experience.selfCheckoutExperience.SelfCheckoutExperiencePackage#getRepeat_Count()
   * @model containment="true"
   * @generated
   */
  IntExpression getCount();

  /**
   * Sets the value of the '{@link self_checkout_experience.selfCheckoutExperience.Repeat#getCount <em>Count</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Count</em>' containment reference.
   * @see #getCount()
   * @generated
   */
  void setCount(IntExpression value);

  /**
   * Returns the value of the '<em><b>Statements</b></em>' containment reference list.
   * The list contents are of type {@link self_checkout_experience.selfCheckoutExperience.PickStatement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statements</em>' containment reference list.
   * @see self_checkout_experience.selfCheckoutExperience.SelfCheckoutExperiencePackage#getRepeat_Statements()
   * @model containment="true"
   * @generated
   */
  EList<PickStatement> getStatements();

} // Repeat
