/**
 * generated by Xtext 2.25.0
 */
package self_checkout_experience.selfCheckoutExperience;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Search</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link self_checkout_experience.selfCheckoutExperience.Search#getItemSearch <em>Item Search</em>}</li>
 *   <li>{@link self_checkout_experience.selfCheckoutExperience.Search#getAddToOnlineBasket <em>Add To Online Basket</em>}</li>
 * </ul>
 *
 * @see self_checkout_experience.selfCheckoutExperience.SelfCheckoutExperiencePackage#getSearch()
 * @model
 * @generated
 */
public interface Search extends EObject
{
  /**
   * Returns the value of the '<em><b>Item Search</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Item Search</em>' containment reference.
   * @see #setItemSearch(ItemDef)
   * @see self_checkout_experience.selfCheckoutExperience.SelfCheckoutExperiencePackage#getSearch_ItemSearch()
   * @model containment="true"
   * @generated
   */
  ItemDef getItemSearch();

  /**
   * Sets the value of the '{@link self_checkout_experience.selfCheckoutExperience.Search#getItemSearch <em>Item Search</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Item Search</em>' containment reference.
   * @see #getItemSearch()
   * @generated
   */
  void setItemSearch(ItemDef value);

  /**
   * Returns the value of the '<em><b>Add To Online Basket</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Add To Online Basket</em>' containment reference.
   * @see #setAddToOnlineBasket(AddToOnlineBasket)
   * @see self_checkout_experience.selfCheckoutExperience.SelfCheckoutExperiencePackage#getSearch_AddToOnlineBasket()
   * @model containment="true"
   * @generated
   */
  AddToOnlineBasket getAddToOnlineBasket();

  /**
   * Sets the value of the '{@link self_checkout_experience.selfCheckoutExperience.Search#getAddToOnlineBasket <em>Add To Online Basket</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Add To Online Basket</em>' containment reference.
   * @see #getAddToOnlineBasket()
   * @generated
   */
  void setAddToOnlineBasket(AddToOnlineBasket value);

} // Search
