/**
 * generated by Xtext 2.25.0
 */
package self_checkout_experience.selfCheckoutExperience;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see self_checkout_experience.selfCheckoutExperience.SelfCheckoutExperienceFactory
 * @model kind="package"
 * @generated
 */
public interface SelfCheckoutExperiencePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "selfCheckoutExperience";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.SelfCheckoutExperience.self_checkout_experience";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "selfCheckoutExperience";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SelfCheckoutExperiencePackage eINSTANCE = self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl.init();

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckoutExperience.impl.Self_checkoutImpl <em>Self checkout</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckoutExperience.impl.Self_checkoutImpl
   * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getSelf_checkout()
   * @generated
   */
  int SELF_CHECKOUT = 0;

  /**
   * The feature id for the '<em><b>Pick Scan Machine</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELF_CHECKOUT__PICK_SCAN_MACHINE = 0;

  /**
   * The feature id for the '<em><b>Pickstatements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELF_CHECKOUT__PICKSTATEMENTS = 1;

  /**
   * The feature id for the '<em><b>Walkstatements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELF_CHECKOUT__WALKSTATEMENTS = 2;

  /**
   * The feature id for the '<em><b>Checkout</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELF_CHECKOUT__CHECKOUT = 3;

  /**
   * The number of structural features of the '<em>Self checkout</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELF_CHECKOUT_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckoutExperience.impl.HoldSelfScannerImpl <em>Hold Self Scanner</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckoutExperience.impl.HoldSelfScannerImpl
   * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getHoldSelfScanner()
   * @generated
   */
  int HOLD_SELF_SCANNER = 1;

  /**
   * The feature id for the '<em><b>Scan Machine</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HOLD_SELF_SCANNER__SCAN_MACHINE = 0;

  /**
   * The number of structural features of the '<em>Hold Self Scanner</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HOLD_SELF_SCANNER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckoutExperience.impl.PickStatementImpl <em>Pick Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckoutExperience.impl.PickStatementImpl
   * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getPickStatement()
   * @generated
   */
  int PICK_STATEMENT = 2;

  /**
   * The feature id for the '<em><b>Item Count</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PICK_STATEMENT__ITEM_COUNT = 0;

  /**
   * The feature id for the '<em><b>Item Picked</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PICK_STATEMENT__ITEM_PICKED = 1;

  /**
   * The feature id for the '<em><b>Holding Item</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PICK_STATEMENT__HOLDING_ITEM = 2;

  /**
   * The number of structural features of the '<em>Pick Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PICK_STATEMENT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckoutExperience.impl.ItemDefImpl <em>Item Def</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckoutExperience.impl.ItemDefImpl
   * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getItemDef()
   * @generated
   */
  int ITEM_DEF = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITEM_DEF__NAME = 0;

  /**
   * The number of structural features of the '<em>Item Def</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITEM_DEF_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckoutExperience.impl.ScanAndAddToBasketImpl <em>Scan And Add To Basket</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckoutExperience.impl.ScanAndAddToBasketImpl
   * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getScanAndAddToBasket()
   * @generated
   */
  int SCAN_AND_ADD_TO_BASKET = 4;

  /**
   * The feature id for the '<em><b>Item In Basket</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCAN_AND_ADD_TO_BASKET__ITEM_IN_BASKET = 0;

  /**
   * The number of structural features of the '<em>Scan And Add To Basket</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCAN_AND_ADD_TO_BASKET_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckoutExperience.impl.DropImpl <em>Drop</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckoutExperience.impl.DropImpl
   * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getDrop()
   * @generated
   */
  int DROP = 5;

  /**
   * The feature id for the '<em><b>Item Dropped</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DROP__ITEM_DROPPED = 0;

  /**
   * The number of structural features of the '<em>Drop</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DROP_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckoutExperience.impl.WalkStatementImpl <em>Walk Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckoutExperience.impl.WalkStatementImpl
   * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getWalkStatement()
   * @generated
   */
  int WALK_STATEMENT = 6;

  /**
   * The number of structural features of the '<em>Walk Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WALK_STATEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckoutExperience.impl.VariableDeclarationImpl <em>Variable Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckoutExperience.impl.VariableDeclarationImpl
   * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getVariableDeclaration()
   * @generated
   */
  int VARIABLE_DECLARATION = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION__NAME = WALK_STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION__VALUE = WALK_STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Variable Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION_FEATURE_COUNT = WALK_STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckoutExperience.impl.RepeatImpl <em>Repeat</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckoutExperience.impl.RepeatImpl
   * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getRepeat()
   * @generated
   */
  int REPEAT = 8;

  /**
   * The feature id for the '<em><b>Count</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REPEAT__COUNT = WALK_STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REPEAT__STATEMENTS = WALK_STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Repeat</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REPEAT_FEATURE_COUNT = WALK_STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckoutExperience.impl.MoveStatementImpl <em>Move Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckoutExperience.impl.MoveStatementImpl
   * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getMoveStatement()
   * @generated
   */
  int MOVE_STATEMENT = 9;

  /**
   * The feature id for the '<em><b>Command</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_STATEMENT__COMMAND = WALK_STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Steps</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_STATEMENT__STEPS = WALK_STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Move Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_STATEMENT_FEATURE_COUNT = WALK_STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckoutExperience.impl.TurnStatementImpl <em>Turn Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckoutExperience.impl.TurnStatementImpl
   * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getTurnStatement()
   * @generated
   */
  int TURN_STATEMENT = 10;

  /**
   * The feature id for the '<em><b>Command</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TURN_STATEMENT__COMMAND = WALK_STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Turn Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TURN_STATEMENT_FEATURE_COUNT = WALK_STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckoutExperience.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckoutExperience.impl.ExpressionImpl
   * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 11;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckoutExperience.impl.IntLiteralImpl <em>Int Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckoutExperience.impl.IntLiteralImpl
   * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getIntLiteral()
   * @generated
   */
  int INT_LITERAL = 12;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LITERAL__VAL = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LITERAL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckoutExperience.impl.IntVarExpressionImpl <em>Int Var Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckoutExperience.impl.IntVarExpressionImpl
   * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getIntVarExpression()
   * @generated
   */
  int INT_VAR_EXPRESSION = 13;

  /**
   * The feature id for the '<em><b>Var</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_VAR_EXPRESSION__VAR = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Var Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_VAR_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckoutExperience.impl.CheckoutImpl <em>Checkout</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckoutExperience.impl.CheckoutImpl
   * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getCheckout()
   * @generated
   */
  int CHECKOUT = 14;

  /**
   * The feature id for the '<em><b>Scan</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECKOUT__SCAN = 0;

  /**
   * The feature id for the '<em><b>Pay</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECKOUT__PAY = 1;

  /**
   * The number of structural features of the '<em>Checkout</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECKOUT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckoutExperience.impl.ScanExpressionImpl <em>Scan Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckoutExperience.impl.ScanExpressionImpl
   * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getScanExpression()
   * @generated
   */
  int SCAN_EXPRESSION = 15;

  /**
   * The number of structural features of the '<em>Scan Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCAN_EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckoutExperience.impl.ScanImpl <em>Scan</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckoutExperience.impl.ScanImpl
   * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getScan()
   * @generated
   */
  int SCAN = 16;

  /**
   * The feature id for the '<em><b>Scan Machine</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCAN__SCAN_MACHINE = SCAN_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Scan</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCAN_FEATURE_COUNT = SCAN_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckoutExperience.impl.CarryItemsImpl <em>Carry Items</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckoutExperience.impl.CarryItemsImpl
   * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getCarryItems()
   * @generated
   */
  int CARRY_ITEMS = 17;

  /**
   * The feature id for the '<em><b>Carry</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARRY_ITEMS__CARRY = 0;

  /**
   * The number of structural features of the '<em>Carry Items</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARRY_ITEMS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckoutExperience.impl.AdditionImpl <em>Addition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckoutExperience.impl.AdditionImpl
   * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getAddition()
   * @generated
   */
  int ADDITION = 18;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION__OPERATOR = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Addition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckoutExperience.impl.MultiplicationImpl <em>Multiplication</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckoutExperience.impl.MultiplicationImpl
   * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getMultiplication()
   * @generated
   */
  int MULTIPLICATION = 19;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION__OPERATOR = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Multiplication</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckoutExperience.impl.ComplexScanImpl <em>Complex Scan</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckoutExperience.impl.ComplexScanImpl
   * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getComplexScan()
   * @generated
   */
  int COMPLEX_SCAN = 20;

  /**
   * The feature id for the '<em><b>Start</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEX_SCAN__START = SCAN_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Next</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEX_SCAN__NEXT = SCAN_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Complex Scan</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEX_SCAN_FEATURE_COUNT = SCAN_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckoutExperience.SelfScanner <em>Self Scanner</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckoutExperience.SelfScanner
   * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getSelfScanner()
   * @generated
   */
  int SELF_SCANNER = 21;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckoutExperience.MoveCommand <em>Move Command</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckoutExperience.MoveCommand
   * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getMoveCommand()
   * @generated
   */
  int MOVE_COMMAND = 22;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckoutExperience.TurnCommand <em>Turn Command</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckoutExperience.TurnCommand
   * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getTurnCommand()
   * @generated
   */
  int TURN_COMMAND = 23;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckoutExperience.Carry <em>Carry</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckoutExperience.Carry
   * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getCarry()
   * @generated
   */
  int CARRY = 24;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckoutExperience.Pay <em>Pay</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckoutExperience.Pay
   * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getPay()
   * @generated
   */
  int PAY = 25;


  /**
   * Returns the meta object for class '{@link self_checkout_experience.selfCheckoutExperience.Self_checkout <em>Self checkout</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Self checkout</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.Self_checkout
   * @generated
   */
  EClass getSelf_checkout();

  /**
   * Returns the meta object for the containment reference '{@link self_checkout_experience.selfCheckoutExperience.Self_checkout#getPickScanMachine <em>Pick Scan Machine</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Pick Scan Machine</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.Self_checkout#getPickScanMachine()
   * @see #getSelf_checkout()
   * @generated
   */
  EReference getSelf_checkout_PickScanMachine();

  /**
   * Returns the meta object for the containment reference list '{@link self_checkout_experience.selfCheckoutExperience.Self_checkout#getPickstatements <em>Pickstatements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Pickstatements</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.Self_checkout#getPickstatements()
   * @see #getSelf_checkout()
   * @generated
   */
  EReference getSelf_checkout_Pickstatements();

  /**
   * Returns the meta object for the containment reference list '{@link self_checkout_experience.selfCheckoutExperience.Self_checkout#getWalkstatements <em>Walkstatements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Walkstatements</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.Self_checkout#getWalkstatements()
   * @see #getSelf_checkout()
   * @generated
   */
  EReference getSelf_checkout_Walkstatements();

  /**
   * Returns the meta object for the containment reference '{@link self_checkout_experience.selfCheckoutExperience.Self_checkout#getCheckout <em>Checkout</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Checkout</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.Self_checkout#getCheckout()
   * @see #getSelf_checkout()
   * @generated
   */
  EReference getSelf_checkout_Checkout();

  /**
   * Returns the meta object for class '{@link self_checkout_experience.selfCheckoutExperience.HoldSelfScanner <em>Hold Self Scanner</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Hold Self Scanner</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.HoldSelfScanner
   * @generated
   */
  EClass getHoldSelfScanner();

  /**
   * Returns the meta object for the attribute '{@link self_checkout_experience.selfCheckoutExperience.HoldSelfScanner#getScanMachine <em>Scan Machine</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Scan Machine</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.HoldSelfScanner#getScanMachine()
   * @see #getHoldSelfScanner()
   * @generated
   */
  EAttribute getHoldSelfScanner_ScanMachine();

  /**
   * Returns the meta object for class '{@link self_checkout_experience.selfCheckoutExperience.PickStatement <em>Pick Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pick Statement</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.PickStatement
   * @generated
   */
  EClass getPickStatement();

  /**
   * Returns the meta object for the containment reference '{@link self_checkout_experience.selfCheckoutExperience.PickStatement#getItemCount <em>Item Count</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Item Count</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.PickStatement#getItemCount()
   * @see #getPickStatement()
   * @generated
   */
  EReference getPickStatement_ItemCount();

  /**
   * Returns the meta object for the containment reference '{@link self_checkout_experience.selfCheckoutExperience.PickStatement#getItemPicked <em>Item Picked</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Item Picked</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.PickStatement#getItemPicked()
   * @see #getPickStatement()
   * @generated
   */
  EReference getPickStatement_ItemPicked();

  /**
   * Returns the meta object for the containment reference '{@link self_checkout_experience.selfCheckoutExperience.PickStatement#getHoldingItem <em>Holding Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Holding Item</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.PickStatement#getHoldingItem()
   * @see #getPickStatement()
   * @generated
   */
  EReference getPickStatement_HoldingItem();

  /**
   * Returns the meta object for class '{@link self_checkout_experience.selfCheckoutExperience.ItemDef <em>Item Def</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Item Def</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.ItemDef
   * @generated
   */
  EClass getItemDef();

  /**
   * Returns the meta object for the attribute '{@link self_checkout_experience.selfCheckoutExperience.ItemDef#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.ItemDef#getName()
   * @see #getItemDef()
   * @generated
   */
  EAttribute getItemDef_Name();

  /**
   * Returns the meta object for class '{@link self_checkout_experience.selfCheckoutExperience.ScanAndAddToBasket <em>Scan And Add To Basket</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Scan And Add To Basket</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.ScanAndAddToBasket
   * @generated
   */
  EClass getScanAndAddToBasket();

  /**
   * Returns the meta object for the reference '{@link self_checkout_experience.selfCheckoutExperience.ScanAndAddToBasket#getItemInBasket <em>Item In Basket</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Item In Basket</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.ScanAndAddToBasket#getItemInBasket()
   * @see #getScanAndAddToBasket()
   * @generated
   */
  EReference getScanAndAddToBasket_ItemInBasket();

  /**
   * Returns the meta object for class '{@link self_checkout_experience.selfCheckoutExperience.Drop <em>Drop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Drop</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.Drop
   * @generated
   */
  EClass getDrop();

  /**
   * Returns the meta object for the reference '{@link self_checkout_experience.selfCheckoutExperience.Drop#getItemDropped <em>Item Dropped</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Item Dropped</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.Drop#getItemDropped()
   * @see #getDrop()
   * @generated
   */
  EReference getDrop_ItemDropped();

  /**
   * Returns the meta object for class '{@link self_checkout_experience.selfCheckoutExperience.WalkStatement <em>Walk Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Walk Statement</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.WalkStatement
   * @generated
   */
  EClass getWalkStatement();

  /**
   * Returns the meta object for class '{@link self_checkout_experience.selfCheckoutExperience.VariableDeclaration <em>Variable Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Declaration</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.VariableDeclaration
   * @generated
   */
  EClass getVariableDeclaration();

  /**
   * Returns the meta object for the attribute '{@link self_checkout_experience.selfCheckoutExperience.VariableDeclaration#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.VariableDeclaration#getName()
   * @see #getVariableDeclaration()
   * @generated
   */
  EAttribute getVariableDeclaration_Name();

  /**
   * Returns the meta object for the attribute '{@link self_checkout_experience.selfCheckoutExperience.VariableDeclaration#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.VariableDeclaration#getValue()
   * @see #getVariableDeclaration()
   * @generated
   */
  EAttribute getVariableDeclaration_Value();

  /**
   * Returns the meta object for class '{@link self_checkout_experience.selfCheckoutExperience.Repeat <em>Repeat</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Repeat</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.Repeat
   * @generated
   */
  EClass getRepeat();

  /**
   * Returns the meta object for the containment reference '{@link self_checkout_experience.selfCheckoutExperience.Repeat#getCount <em>Count</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Count</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.Repeat#getCount()
   * @see #getRepeat()
   * @generated
   */
  EReference getRepeat_Count();

  /**
   * Returns the meta object for the containment reference list '{@link self_checkout_experience.selfCheckoutExperience.Repeat#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.Repeat#getStatements()
   * @see #getRepeat()
   * @generated
   */
  EReference getRepeat_Statements();

  /**
   * Returns the meta object for class '{@link self_checkout_experience.selfCheckoutExperience.MoveStatement <em>Move Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Move Statement</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.MoveStatement
   * @generated
   */
  EClass getMoveStatement();

  /**
   * Returns the meta object for the attribute '{@link self_checkout_experience.selfCheckoutExperience.MoveStatement#getCommand <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Command</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.MoveStatement#getCommand()
   * @see #getMoveStatement()
   * @generated
   */
  EAttribute getMoveStatement_Command();

  /**
   * Returns the meta object for the containment reference '{@link self_checkout_experience.selfCheckoutExperience.MoveStatement#getSteps <em>Steps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Steps</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.MoveStatement#getSteps()
   * @see #getMoveStatement()
   * @generated
   */
  EReference getMoveStatement_Steps();

  /**
   * Returns the meta object for class '{@link self_checkout_experience.selfCheckoutExperience.TurnStatement <em>Turn Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Turn Statement</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.TurnStatement
   * @generated
   */
  EClass getTurnStatement();

  /**
   * Returns the meta object for the attribute '{@link self_checkout_experience.selfCheckoutExperience.TurnStatement#getCommand <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Command</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.TurnStatement#getCommand()
   * @see #getTurnStatement()
   * @generated
   */
  EAttribute getTurnStatement_Command();

  /**
   * Returns the meta object for class '{@link self_checkout_experience.selfCheckoutExperience.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link self_checkout_experience.selfCheckoutExperience.IntLiteral <em>Int Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Literal</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.IntLiteral
   * @generated
   */
  EClass getIntLiteral();

  /**
   * Returns the meta object for the attribute '{@link self_checkout_experience.selfCheckoutExperience.IntLiteral#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.IntLiteral#getVal()
   * @see #getIntLiteral()
   * @generated
   */
  EAttribute getIntLiteral_Val();

  /**
   * Returns the meta object for class '{@link self_checkout_experience.selfCheckoutExperience.IntVarExpression <em>Int Var Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Var Expression</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.IntVarExpression
   * @generated
   */
  EClass getIntVarExpression();

  /**
   * Returns the meta object for the reference '{@link self_checkout_experience.selfCheckoutExperience.IntVarExpression#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Var</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.IntVarExpression#getVar()
   * @see #getIntVarExpression()
   * @generated
   */
  EReference getIntVarExpression_Var();

  /**
   * Returns the meta object for class '{@link self_checkout_experience.selfCheckoutExperience.Checkout <em>Checkout</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Checkout</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.Checkout
   * @generated
   */
  EClass getCheckout();

  /**
   * Returns the meta object for the containment reference '{@link self_checkout_experience.selfCheckoutExperience.Checkout#getScan <em>Scan</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Scan</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.Checkout#getScan()
   * @see #getCheckout()
   * @generated
   */
  EReference getCheckout_Scan();

  /**
   * Returns the meta object for the attribute '{@link self_checkout_experience.selfCheckoutExperience.Checkout#getPay <em>Pay</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Pay</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.Checkout#getPay()
   * @see #getCheckout()
   * @generated
   */
  EAttribute getCheckout_Pay();

  /**
   * Returns the meta object for class '{@link self_checkout_experience.selfCheckoutExperience.ScanExpression <em>Scan Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Scan Expression</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.ScanExpression
   * @generated
   */
  EClass getScanExpression();

  /**
   * Returns the meta object for class '{@link self_checkout_experience.selfCheckoutExperience.Scan <em>Scan</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Scan</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.Scan
   * @generated
   */
  EClass getScan();

  /**
   * Returns the meta object for the attribute '{@link self_checkout_experience.selfCheckoutExperience.Scan#getScanMachine <em>Scan Machine</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Scan Machine</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.Scan#getScanMachine()
   * @see #getScan()
   * @generated
   */
  EAttribute getScan_ScanMachine();

  /**
   * Returns the meta object for class '{@link self_checkout_experience.selfCheckoutExperience.CarryItems <em>Carry Items</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Carry Items</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.CarryItems
   * @generated
   */
  EClass getCarryItems();

  /**
   * Returns the meta object for the attribute '{@link self_checkout_experience.selfCheckoutExperience.CarryItems#getCarry <em>Carry</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Carry</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.CarryItems#getCarry()
   * @see #getCarryItems()
   * @generated
   */
  EAttribute getCarryItems_Carry();

  /**
   * Returns the meta object for class '{@link self_checkout_experience.selfCheckoutExperience.Addition <em>Addition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Addition</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.Addition
   * @generated
   */
  EClass getAddition();

  /**
   * Returns the meta object for the containment reference '{@link self_checkout_experience.selfCheckoutExperience.Addition#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.Addition#getLeft()
   * @see #getAddition()
   * @generated
   */
  EReference getAddition_Left();

  /**
   * Returns the meta object for the attribute list '{@link self_checkout_experience.selfCheckoutExperience.Addition#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Operator</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.Addition#getOperator()
   * @see #getAddition()
   * @generated
   */
  EAttribute getAddition_Operator();

  /**
   * Returns the meta object for the containment reference list '{@link self_checkout_experience.selfCheckoutExperience.Addition#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Right</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.Addition#getRight()
   * @see #getAddition()
   * @generated
   */
  EReference getAddition_Right();

  /**
   * Returns the meta object for class '{@link self_checkout_experience.selfCheckoutExperience.Multiplication <em>Multiplication</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Multiplication</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.Multiplication
   * @generated
   */
  EClass getMultiplication();

  /**
   * Returns the meta object for the containment reference '{@link self_checkout_experience.selfCheckoutExperience.Multiplication#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.Multiplication#getLeft()
   * @see #getMultiplication()
   * @generated
   */
  EReference getMultiplication_Left();

  /**
   * Returns the meta object for the attribute list '{@link self_checkout_experience.selfCheckoutExperience.Multiplication#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Operator</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.Multiplication#getOperator()
   * @see #getMultiplication()
   * @generated
   */
  EAttribute getMultiplication_Operator();

  /**
   * Returns the meta object for the containment reference list '{@link self_checkout_experience.selfCheckoutExperience.Multiplication#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Right</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.Multiplication#getRight()
   * @see #getMultiplication()
   * @generated
   */
  EReference getMultiplication_Right();

  /**
   * Returns the meta object for class '{@link self_checkout_experience.selfCheckoutExperience.ComplexScan <em>Complex Scan</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Complex Scan</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.ComplexScan
   * @generated
   */
  EClass getComplexScan();

  /**
   * Returns the meta object for the containment reference '{@link self_checkout_experience.selfCheckoutExperience.ComplexScan#getStart <em>Start</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Start</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.ComplexScan#getStart()
   * @see #getComplexScan()
   * @generated
   */
  EReference getComplexScan_Start();

  /**
   * Returns the meta object for the containment reference list '{@link self_checkout_experience.selfCheckoutExperience.ComplexScan#getNext <em>Next</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Next</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.ComplexScan#getNext()
   * @see #getComplexScan()
   * @generated
   */
  EReference getComplexScan_Next();

  /**
   * Returns the meta object for enum '{@link self_checkout_experience.selfCheckoutExperience.SelfScanner <em>Self Scanner</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Self Scanner</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.SelfScanner
   * @generated
   */
  EEnum getSelfScanner();

  /**
   * Returns the meta object for enum '{@link self_checkout_experience.selfCheckoutExperience.MoveCommand <em>Move Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Move Command</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.MoveCommand
   * @generated
   */
  EEnum getMoveCommand();

  /**
   * Returns the meta object for enum '{@link self_checkout_experience.selfCheckoutExperience.TurnCommand <em>Turn Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Turn Command</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.TurnCommand
   * @generated
   */
  EEnum getTurnCommand();

  /**
   * Returns the meta object for enum '{@link self_checkout_experience.selfCheckoutExperience.Carry <em>Carry</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Carry</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.Carry
   * @generated
   */
  EEnum getCarry();

  /**
   * Returns the meta object for enum '{@link self_checkout_experience.selfCheckoutExperience.Pay <em>Pay</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Pay</em>'.
   * @see self_checkout_experience.selfCheckoutExperience.Pay
   * @generated
   */
  EEnum getPay();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SelfCheckoutExperienceFactory getSelfCheckoutExperienceFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckoutExperience.impl.Self_checkoutImpl <em>Self checkout</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckoutExperience.impl.Self_checkoutImpl
     * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getSelf_checkout()
     * @generated
     */
    EClass SELF_CHECKOUT = eINSTANCE.getSelf_checkout();

    /**
     * The meta object literal for the '<em><b>Pick Scan Machine</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELF_CHECKOUT__PICK_SCAN_MACHINE = eINSTANCE.getSelf_checkout_PickScanMachine();

    /**
     * The meta object literal for the '<em><b>Pickstatements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELF_CHECKOUT__PICKSTATEMENTS = eINSTANCE.getSelf_checkout_Pickstatements();

    /**
     * The meta object literal for the '<em><b>Walkstatements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELF_CHECKOUT__WALKSTATEMENTS = eINSTANCE.getSelf_checkout_Walkstatements();

    /**
     * The meta object literal for the '<em><b>Checkout</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELF_CHECKOUT__CHECKOUT = eINSTANCE.getSelf_checkout_Checkout();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckoutExperience.impl.HoldSelfScannerImpl <em>Hold Self Scanner</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckoutExperience.impl.HoldSelfScannerImpl
     * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getHoldSelfScanner()
     * @generated
     */
    EClass HOLD_SELF_SCANNER = eINSTANCE.getHoldSelfScanner();

    /**
     * The meta object literal for the '<em><b>Scan Machine</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HOLD_SELF_SCANNER__SCAN_MACHINE = eINSTANCE.getHoldSelfScanner_ScanMachine();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckoutExperience.impl.PickStatementImpl <em>Pick Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckoutExperience.impl.PickStatementImpl
     * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getPickStatement()
     * @generated
     */
    EClass PICK_STATEMENT = eINSTANCE.getPickStatement();

    /**
     * The meta object literal for the '<em><b>Item Count</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PICK_STATEMENT__ITEM_COUNT = eINSTANCE.getPickStatement_ItemCount();

    /**
     * The meta object literal for the '<em><b>Item Picked</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PICK_STATEMENT__ITEM_PICKED = eINSTANCE.getPickStatement_ItemPicked();

    /**
     * The meta object literal for the '<em><b>Holding Item</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PICK_STATEMENT__HOLDING_ITEM = eINSTANCE.getPickStatement_HoldingItem();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckoutExperience.impl.ItemDefImpl <em>Item Def</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckoutExperience.impl.ItemDefImpl
     * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getItemDef()
     * @generated
     */
    EClass ITEM_DEF = eINSTANCE.getItemDef();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ITEM_DEF__NAME = eINSTANCE.getItemDef_Name();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckoutExperience.impl.ScanAndAddToBasketImpl <em>Scan And Add To Basket</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckoutExperience.impl.ScanAndAddToBasketImpl
     * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getScanAndAddToBasket()
     * @generated
     */
    EClass SCAN_AND_ADD_TO_BASKET = eINSTANCE.getScanAndAddToBasket();

    /**
     * The meta object literal for the '<em><b>Item In Basket</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCAN_AND_ADD_TO_BASKET__ITEM_IN_BASKET = eINSTANCE.getScanAndAddToBasket_ItemInBasket();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckoutExperience.impl.DropImpl <em>Drop</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckoutExperience.impl.DropImpl
     * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getDrop()
     * @generated
     */
    EClass DROP = eINSTANCE.getDrop();

    /**
     * The meta object literal for the '<em><b>Item Dropped</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DROP__ITEM_DROPPED = eINSTANCE.getDrop_ItemDropped();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckoutExperience.impl.WalkStatementImpl <em>Walk Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckoutExperience.impl.WalkStatementImpl
     * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getWalkStatement()
     * @generated
     */
    EClass WALK_STATEMENT = eINSTANCE.getWalkStatement();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckoutExperience.impl.VariableDeclarationImpl <em>Variable Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckoutExperience.impl.VariableDeclarationImpl
     * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getVariableDeclaration()
     * @generated
     */
    EClass VARIABLE_DECLARATION = eINSTANCE.getVariableDeclaration();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_DECLARATION__NAME = eINSTANCE.getVariableDeclaration_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_DECLARATION__VALUE = eINSTANCE.getVariableDeclaration_Value();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckoutExperience.impl.RepeatImpl <em>Repeat</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckoutExperience.impl.RepeatImpl
     * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getRepeat()
     * @generated
     */
    EClass REPEAT = eINSTANCE.getRepeat();

    /**
     * The meta object literal for the '<em><b>Count</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REPEAT__COUNT = eINSTANCE.getRepeat_Count();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REPEAT__STATEMENTS = eINSTANCE.getRepeat_Statements();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckoutExperience.impl.MoveStatementImpl <em>Move Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckoutExperience.impl.MoveStatementImpl
     * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getMoveStatement()
     * @generated
     */
    EClass MOVE_STATEMENT = eINSTANCE.getMoveStatement();

    /**
     * The meta object literal for the '<em><b>Command</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOVE_STATEMENT__COMMAND = eINSTANCE.getMoveStatement_Command();

    /**
     * The meta object literal for the '<em><b>Steps</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MOVE_STATEMENT__STEPS = eINSTANCE.getMoveStatement_Steps();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckoutExperience.impl.TurnStatementImpl <em>Turn Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckoutExperience.impl.TurnStatementImpl
     * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getTurnStatement()
     * @generated
     */
    EClass TURN_STATEMENT = eINSTANCE.getTurnStatement();

    /**
     * The meta object literal for the '<em><b>Command</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TURN_STATEMENT__COMMAND = eINSTANCE.getTurnStatement_Command();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckoutExperience.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckoutExperience.impl.ExpressionImpl
     * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckoutExperience.impl.IntLiteralImpl <em>Int Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckoutExperience.impl.IntLiteralImpl
     * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getIntLiteral()
     * @generated
     */
    EClass INT_LITERAL = eINSTANCE.getIntLiteral();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT_LITERAL__VAL = eINSTANCE.getIntLiteral_Val();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckoutExperience.impl.IntVarExpressionImpl <em>Int Var Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckoutExperience.impl.IntVarExpressionImpl
     * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getIntVarExpression()
     * @generated
     */
    EClass INT_VAR_EXPRESSION = eINSTANCE.getIntVarExpression();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INT_VAR_EXPRESSION__VAR = eINSTANCE.getIntVarExpression_Var();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckoutExperience.impl.CheckoutImpl <em>Checkout</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckoutExperience.impl.CheckoutImpl
     * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getCheckout()
     * @generated
     */
    EClass CHECKOUT = eINSTANCE.getCheckout();

    /**
     * The meta object literal for the '<em><b>Scan</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHECKOUT__SCAN = eINSTANCE.getCheckout_Scan();

    /**
     * The meta object literal for the '<em><b>Pay</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHECKOUT__PAY = eINSTANCE.getCheckout_Pay();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckoutExperience.impl.ScanExpressionImpl <em>Scan Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckoutExperience.impl.ScanExpressionImpl
     * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getScanExpression()
     * @generated
     */
    EClass SCAN_EXPRESSION = eINSTANCE.getScanExpression();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckoutExperience.impl.ScanImpl <em>Scan</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckoutExperience.impl.ScanImpl
     * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getScan()
     * @generated
     */
    EClass SCAN = eINSTANCE.getScan();

    /**
     * The meta object literal for the '<em><b>Scan Machine</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCAN__SCAN_MACHINE = eINSTANCE.getScan_ScanMachine();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckoutExperience.impl.CarryItemsImpl <em>Carry Items</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckoutExperience.impl.CarryItemsImpl
     * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getCarryItems()
     * @generated
     */
    EClass CARRY_ITEMS = eINSTANCE.getCarryItems();

    /**
     * The meta object literal for the '<em><b>Carry</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CARRY_ITEMS__CARRY = eINSTANCE.getCarryItems_Carry();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckoutExperience.impl.AdditionImpl <em>Addition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckoutExperience.impl.AdditionImpl
     * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getAddition()
     * @generated
     */
    EClass ADDITION = eINSTANCE.getAddition();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADDITION__LEFT = eINSTANCE.getAddition_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ADDITION__OPERATOR = eINSTANCE.getAddition_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADDITION__RIGHT = eINSTANCE.getAddition_Right();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckoutExperience.impl.MultiplicationImpl <em>Multiplication</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckoutExperience.impl.MultiplicationImpl
     * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getMultiplication()
     * @generated
     */
    EClass MULTIPLICATION = eINSTANCE.getMultiplication();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTIPLICATION__LEFT = eINSTANCE.getMultiplication_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MULTIPLICATION__OPERATOR = eINSTANCE.getMultiplication_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTIPLICATION__RIGHT = eINSTANCE.getMultiplication_Right();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckoutExperience.impl.ComplexScanImpl <em>Complex Scan</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckoutExperience.impl.ComplexScanImpl
     * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getComplexScan()
     * @generated
     */
    EClass COMPLEX_SCAN = eINSTANCE.getComplexScan();

    /**
     * The meta object literal for the '<em><b>Start</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPLEX_SCAN__START = eINSTANCE.getComplexScan_Start();

    /**
     * The meta object literal for the '<em><b>Next</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPLEX_SCAN__NEXT = eINSTANCE.getComplexScan_Next();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckoutExperience.SelfScanner <em>Self Scanner</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckoutExperience.SelfScanner
     * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getSelfScanner()
     * @generated
     */
    EEnum SELF_SCANNER = eINSTANCE.getSelfScanner();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckoutExperience.MoveCommand <em>Move Command</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckoutExperience.MoveCommand
     * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getMoveCommand()
     * @generated
     */
    EEnum MOVE_COMMAND = eINSTANCE.getMoveCommand();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckoutExperience.TurnCommand <em>Turn Command</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckoutExperience.TurnCommand
     * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getTurnCommand()
     * @generated
     */
    EEnum TURN_COMMAND = eINSTANCE.getTurnCommand();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckoutExperience.Carry <em>Carry</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckoutExperience.Carry
     * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getCarry()
     * @generated
     */
    EEnum CARRY = eINSTANCE.getCarry();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckoutExperience.Pay <em>Pay</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckoutExperience.Pay
     * @see self_checkout_experience.selfCheckoutExperience.impl.SelfCheckoutExperiencePackageImpl#getPay()
     * @generated
     */
    EEnum PAY = eINSTANCE.getPay();

  }

} //SelfCheckoutExperiencePackage
