/**
 * generated by Xtext 2.25.0
 */
package self_checkout_experience.selfCheckoutExperience;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Turn Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link self_checkout_experience.selfCheckoutExperience.TurnStatement#getCommand <em>Command</em>}</li>
 *   <li>{@link self_checkout_experience.selfCheckoutExperience.TurnStatement#getDegrees <em>Degrees</em>}</li>
 * </ul>
 *
 * @see self_checkout_experience.selfCheckoutExperience.SelfCheckoutExperiencePackage#getTurnStatement()
 * @model
 * @generated
 */
public interface TurnStatement extends WalkStatement
{
  /**
   * Returns the value of the '<em><b>Command</b></em>' attribute.
   * The literals are from the enumeration {@link self_checkout_experience.selfCheckoutExperience.TurnCommand}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Command</em>' attribute.
   * @see self_checkout_experience.selfCheckoutExperience.TurnCommand
   * @see #setCommand(TurnCommand)
   * @see self_checkout_experience.selfCheckoutExperience.SelfCheckoutExperiencePackage#getTurnStatement_Command()
   * @model
   * @generated
   */
  TurnCommand getCommand();

  /**
   * Sets the value of the '{@link self_checkout_experience.selfCheckoutExperience.TurnStatement#getCommand <em>Command</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Command</em>' attribute.
   * @see self_checkout_experience.selfCheckoutExperience.TurnCommand
   * @see #getCommand()
   * @generated
   */
  void setCommand(TurnCommand value);

  /**
   * Returns the value of the '<em><b>Degrees</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Degrees</em>' containment reference.
   * @see #setDegrees(Expression)
   * @see self_checkout_experience.selfCheckoutExperience.SelfCheckoutExperiencePackage#getTurnStatement_Degrees()
   * @model containment="true"
   * @generated
   */
  Expression getDegrees();

  /**
   * Sets the value of the '{@link self_checkout_experience.selfCheckoutExperience.TurnStatement#getDegrees <em>Degrees</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Degrees</em>' containment reference.
   * @see #getDegrees()
   * @generated
   */
  void setDegrees(Expression value);

} // TurnStatement
