/**
 * generated by Xtext 2.25.0
 */
package self_checkout_experience.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class SelfCheckoutExperienceIdeModule extends AbstractSelfCheckoutExperienceIdeModule {
}
