/**
 * generated by Xtext 2.25.0
 */
package self_checkout_experience.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class SelfCheckoutExperienceUiModule extends AbstractSelfCheckoutExperienceUiModule {
  public SelfCheckoutExperienceUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
