/**
 * generated by Xtext 2.25.0
 */
package self_checkout_experience.selfCheckout;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Browsing</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link self_checkout_experience.selfCheckout.Browsing#getChoose <em>Choose</em>}</li>
 *   <li>{@link self_checkout_experience.selfCheckout.Browsing#getWalkstatements <em>Walkstatements</em>}</li>
 * </ul>
 *
 * @see self_checkout_experience.selfCheckout.SelfCheckoutPackage#getBrowsing()
 * @model
 * @generated
 */
public interface Browsing extends EObject
{
  /**
   * Returns the value of the '<em><b>Choose</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Choose</em>' containment reference.
   * @see #setChoose(Choose)
   * @see self_checkout_experience.selfCheckout.SelfCheckoutPackage#getBrowsing_Choose()
   * @model containment="true"
   * @generated
   */
  Choose getChoose();

  /**
   * Sets the value of the '{@link self_checkout_experience.selfCheckout.Browsing#getChoose <em>Choose</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Choose</em>' containment reference.
   * @see #getChoose()
   * @generated
   */
  void setChoose(Choose value);

  /**
   * Returns the value of the '<em><b>Walkstatements</b></em>' containment reference list.
   * The list contents are of type {@link self_checkout_experience.selfCheckout.WalkStatement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Walkstatements</em>' containment reference list.
   * @see self_checkout_experience.selfCheckout.SelfCheckoutPackage#getBrowsing_Walkstatements()
   * @model containment="true"
   * @generated
   */
  EList<WalkStatement> getWalkstatements();

} // Browsing
