/**
 * generated by Xtext 2.25.0
 */
package self_checkout_experience.selfCheckout;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see self_checkout_experience.selfCheckout.SelfCheckoutFactory
 * @model kind="package"
 * @generated
 */
public interface SelfCheckoutPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "selfCheckout";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.SelfCheckout.self_checkout_experience";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "selfCheckout";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SelfCheckoutPackage eINSTANCE = self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl.init();

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckout.impl.Self_checkoutImpl <em>Self checkout</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckout.impl.Self_checkoutImpl
   * @see self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl#getSelf_checkout()
   * @generated
   */
  int SELF_CHECKOUT = 0;

  /**
   * The feature id for the '<em><b>Pick</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELF_CHECKOUT__PICK = 0;

  /**
   * The feature id for the '<em><b>Walkstatements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELF_CHECKOUT__WALKSTATEMENTS = 1;

  /**
   * The feature id for the '<em><b>Checkout</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELF_CHECKOUT__CHECKOUT = 2;

  /**
   * The number of structural features of the '<em>Self checkout</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELF_CHECKOUT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckout.impl.PickImpl <em>Pick</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckout.impl.PickImpl
   * @see self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl#getPick()
   * @generated
   */
  int PICK = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PICK__NAME = 0;

  /**
   * The feature id for the '<em><b>Holding Item</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PICK__HOLDING_ITEM = 1;

  /**
   * The number of structural features of the '<em>Pick</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PICK_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckout.impl.AddToBasketImpl <em>Add To Basket</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckout.impl.AddToBasketImpl
   * @see self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl#getAddToBasket()
   * @generated
   */
  int ADD_TO_BASKET = 2;

  /**
   * The feature id for the '<em><b>Item</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_TO_BASKET__ITEM = 0;

  /**
   * The number of structural features of the '<em>Add To Basket</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_TO_BASKET_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckout.impl.DropImpl <em>Drop</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckout.impl.DropImpl
   * @see self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl#getDrop()
   * @generated
   */
  int DROP = 3;

  /**
   * The feature id for the '<em><b>Item</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DROP__ITEM = 0;

  /**
   * The number of structural features of the '<em>Drop</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DROP_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckout.impl.WalkStatementImpl <em>Walk Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckout.impl.WalkStatementImpl
   * @see self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl#getWalkStatement()
   * @generated
   */
  int WALK_STATEMENT = 4;

  /**
   * The number of structural features of the '<em>Walk Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WALK_STATEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckout.impl.VariableDeclarationImpl <em>Variable Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckout.impl.VariableDeclarationImpl
   * @see self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl#getVariableDeclaration()
   * @generated
   */
  int VARIABLE_DECLARATION = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION__NAME = WALK_STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION__VALUE = WALK_STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Variable Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION_FEATURE_COUNT = WALK_STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckout.impl.LoopStatementImpl <em>Loop Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckout.impl.LoopStatementImpl
   * @see self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl#getLoopStatement()
   * @generated
   */
  int LOOP_STATEMENT = 6;

  /**
   * The feature id for the '<em><b>Count</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP_STATEMENT__COUNT = WALK_STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP_STATEMENT__STATEMENTS = WALK_STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Loop Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP_STATEMENT_FEATURE_COUNT = WALK_STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckout.impl.MoveStatementImpl <em>Move Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckout.impl.MoveStatementImpl
   * @see self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl#getMoveStatement()
   * @generated
   */
  int MOVE_STATEMENT = 7;

  /**
   * The feature id for the '<em><b>Command</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_STATEMENT__COMMAND = WALK_STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Steps</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_STATEMENT__STEPS = WALK_STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Move Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVE_STATEMENT_FEATURE_COUNT = WALK_STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckout.impl.TurnStatementImpl <em>Turn Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckout.impl.TurnStatementImpl
   * @see self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl#getTurnStatement()
   * @generated
   */
  int TURN_STATEMENT = 8;

  /**
   * The feature id for the '<em><b>Command</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TURN_STATEMENT__COMMAND = WALK_STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Degrees</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TURN_STATEMENT__DEGREES = WALK_STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Turn Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TURN_STATEMENT_FEATURE_COUNT = WALK_STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckout.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckout.impl.ExpressionImpl
   * @see self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 9;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckout.impl.IntLiteralImpl <em>Int Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckout.impl.IntLiteralImpl
   * @see self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl#getIntLiteral()
   * @generated
   */
  int INT_LITERAL = 10;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LITERAL__VAL = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LITERAL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckout.impl.RealLiteralImpl <em>Real Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckout.impl.RealLiteralImpl
   * @see self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl#getRealLiteral()
   * @generated
   */
  int REAL_LITERAL = 11;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REAL_LITERAL__VAL = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Real Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REAL_LITERAL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckout.impl.IntVarExpressionImpl <em>Int Var Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckout.impl.IntVarExpressionImpl
   * @see self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl#getIntVarExpression()
   * @generated
   */
  int INT_VAR_EXPRESSION = 12;

  /**
   * The feature id for the '<em><b>Var</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_VAR_EXPRESSION__VAR = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Var Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_VAR_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckout.impl.CheckoutImpl <em>Checkout</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckout.impl.CheckoutImpl
   * @see self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl#getCheckout()
   * @generated
   */
  int CHECKOUT = 13;

  /**
   * The feature id for the '<em><b>Scan</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECKOUT__SCAN = 0;

  /**
   * The feature id for the '<em><b>Pay</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECKOUT__PAY = 1;

  /**
   * The number of structural features of the '<em>Checkout</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECKOUT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckout.impl.ScanImpl <em>Scan</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckout.impl.ScanImpl
   * @see self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl#getScan()
   * @generated
   */
  int SCAN = 14;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCAN__NAME = 0;

  /**
   * The feature id for the '<em><b>Add To Bag</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCAN__ADD_TO_BAG = 1;

  /**
   * The number of structural features of the '<em>Scan</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCAN_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckout.impl.AddToBagImpl <em>Add To Bag</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckout.impl.AddToBagImpl
   * @see self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl#getAddToBag()
   * @generated
   */
  int ADD_TO_BAG = 15;

  /**
   * The feature id for the '<em><b>Bag Item</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_TO_BAG__BAG_ITEM = 0;

  /**
   * The number of structural features of the '<em>Add To Bag</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_TO_BAG_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckout.impl.AdditionImpl <em>Addition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckout.impl.AdditionImpl
   * @see self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl#getAddition()
   * @generated
   */
  int ADDITION = 16;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION__OPERATOR = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Addition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckout.impl.MultiplicationImpl <em>Multiplication</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckout.impl.MultiplicationImpl
   * @see self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl#getMultiplication()
   * @generated
   */
  int MULTIPLICATION = 17;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION__OPERATOR = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Multiplication</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckout.MoveCommand <em>Move Command</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckout.MoveCommand
   * @see self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl#getMoveCommand()
   * @generated
   */
  int MOVE_COMMAND = 18;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckout.TurnCommand <em>Turn Command</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckout.TurnCommand
   * @see self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl#getTurnCommand()
   * @generated
   */
  int TURN_COMMAND = 19;

  /**
   * The meta object id for the '{@link self_checkout_experience.selfCheckout.Pay <em>Pay</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see self_checkout_experience.selfCheckout.Pay
   * @see self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl#getPay()
   * @generated
   */
  int PAY = 20;


  /**
   * Returns the meta object for class '{@link self_checkout_experience.selfCheckout.Self_checkout <em>Self checkout</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Self checkout</em>'.
   * @see self_checkout_experience.selfCheckout.Self_checkout
   * @generated
   */
  EClass getSelf_checkout();

  /**
   * Returns the meta object for the containment reference list '{@link self_checkout_experience.selfCheckout.Self_checkout#getPick <em>Pick</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Pick</em>'.
   * @see self_checkout_experience.selfCheckout.Self_checkout#getPick()
   * @see #getSelf_checkout()
   * @generated
   */
  EReference getSelf_checkout_Pick();

  /**
   * Returns the meta object for the containment reference list '{@link self_checkout_experience.selfCheckout.Self_checkout#getWalkstatements <em>Walkstatements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Walkstatements</em>'.
   * @see self_checkout_experience.selfCheckout.Self_checkout#getWalkstatements()
   * @see #getSelf_checkout()
   * @generated
   */
  EReference getSelf_checkout_Walkstatements();

  /**
   * Returns the meta object for the containment reference '{@link self_checkout_experience.selfCheckout.Self_checkout#getCheckout <em>Checkout</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Checkout</em>'.
   * @see self_checkout_experience.selfCheckout.Self_checkout#getCheckout()
   * @see #getSelf_checkout()
   * @generated
   */
  EReference getSelf_checkout_Checkout();

  /**
   * Returns the meta object for class '{@link self_checkout_experience.selfCheckout.Pick <em>Pick</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pick</em>'.
   * @see self_checkout_experience.selfCheckout.Pick
   * @generated
   */
  EClass getPick();

  /**
   * Returns the meta object for the attribute '{@link self_checkout_experience.selfCheckout.Pick#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see self_checkout_experience.selfCheckout.Pick#getName()
   * @see #getPick()
   * @generated
   */
  EAttribute getPick_Name();

  /**
   * Returns the meta object for the containment reference '{@link self_checkout_experience.selfCheckout.Pick#getHoldingItem <em>Holding Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Holding Item</em>'.
   * @see self_checkout_experience.selfCheckout.Pick#getHoldingItem()
   * @see #getPick()
   * @generated
   */
  EReference getPick_HoldingItem();

  /**
   * Returns the meta object for class '{@link self_checkout_experience.selfCheckout.AddToBasket <em>Add To Basket</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Add To Basket</em>'.
   * @see self_checkout_experience.selfCheckout.AddToBasket
   * @generated
   */
  EClass getAddToBasket();

  /**
   * Returns the meta object for the reference '{@link self_checkout_experience.selfCheckout.AddToBasket#getItem <em>Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Item</em>'.
   * @see self_checkout_experience.selfCheckout.AddToBasket#getItem()
   * @see #getAddToBasket()
   * @generated
   */
  EReference getAddToBasket_Item();

  /**
   * Returns the meta object for class '{@link self_checkout_experience.selfCheckout.Drop <em>Drop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Drop</em>'.
   * @see self_checkout_experience.selfCheckout.Drop
   * @generated
   */
  EClass getDrop();

  /**
   * Returns the meta object for the reference '{@link self_checkout_experience.selfCheckout.Drop#getItem <em>Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Item</em>'.
   * @see self_checkout_experience.selfCheckout.Drop#getItem()
   * @see #getDrop()
   * @generated
   */
  EReference getDrop_Item();

  /**
   * Returns the meta object for class '{@link self_checkout_experience.selfCheckout.WalkStatement <em>Walk Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Walk Statement</em>'.
   * @see self_checkout_experience.selfCheckout.WalkStatement
   * @generated
   */
  EClass getWalkStatement();

  /**
   * Returns the meta object for class '{@link self_checkout_experience.selfCheckout.VariableDeclaration <em>Variable Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Declaration</em>'.
   * @see self_checkout_experience.selfCheckout.VariableDeclaration
   * @generated
   */
  EClass getVariableDeclaration();

  /**
   * Returns the meta object for the attribute '{@link self_checkout_experience.selfCheckout.VariableDeclaration#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see self_checkout_experience.selfCheckout.VariableDeclaration#getName()
   * @see #getVariableDeclaration()
   * @generated
   */
  EAttribute getVariableDeclaration_Name();

  /**
   * Returns the meta object for the attribute '{@link self_checkout_experience.selfCheckout.VariableDeclaration#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see self_checkout_experience.selfCheckout.VariableDeclaration#getValue()
   * @see #getVariableDeclaration()
   * @generated
   */
  EAttribute getVariableDeclaration_Value();

  /**
   * Returns the meta object for class '{@link self_checkout_experience.selfCheckout.LoopStatement <em>Loop Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Loop Statement</em>'.
   * @see self_checkout_experience.selfCheckout.LoopStatement
   * @generated
   */
  EClass getLoopStatement();

  /**
   * Returns the meta object for the containment reference '{@link self_checkout_experience.selfCheckout.LoopStatement#getCount <em>Count</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Count</em>'.
   * @see self_checkout_experience.selfCheckout.LoopStatement#getCount()
   * @see #getLoopStatement()
   * @generated
   */
  EReference getLoopStatement_Count();

  /**
   * Returns the meta object for the containment reference list '{@link self_checkout_experience.selfCheckout.LoopStatement#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see self_checkout_experience.selfCheckout.LoopStatement#getStatements()
   * @see #getLoopStatement()
   * @generated
   */
  EReference getLoopStatement_Statements();

  /**
   * Returns the meta object for class '{@link self_checkout_experience.selfCheckout.MoveStatement <em>Move Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Move Statement</em>'.
   * @see self_checkout_experience.selfCheckout.MoveStatement
   * @generated
   */
  EClass getMoveStatement();

  /**
   * Returns the meta object for the attribute '{@link self_checkout_experience.selfCheckout.MoveStatement#getCommand <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Command</em>'.
   * @see self_checkout_experience.selfCheckout.MoveStatement#getCommand()
   * @see #getMoveStatement()
   * @generated
   */
  EAttribute getMoveStatement_Command();

  /**
   * Returns the meta object for the containment reference '{@link self_checkout_experience.selfCheckout.MoveStatement#getSteps <em>Steps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Steps</em>'.
   * @see self_checkout_experience.selfCheckout.MoveStatement#getSteps()
   * @see #getMoveStatement()
   * @generated
   */
  EReference getMoveStatement_Steps();

  /**
   * Returns the meta object for class '{@link self_checkout_experience.selfCheckout.TurnStatement <em>Turn Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Turn Statement</em>'.
   * @see self_checkout_experience.selfCheckout.TurnStatement
   * @generated
   */
  EClass getTurnStatement();

  /**
   * Returns the meta object for the attribute '{@link self_checkout_experience.selfCheckout.TurnStatement#getCommand <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Command</em>'.
   * @see self_checkout_experience.selfCheckout.TurnStatement#getCommand()
   * @see #getTurnStatement()
   * @generated
   */
  EAttribute getTurnStatement_Command();

  /**
   * Returns the meta object for the containment reference '{@link self_checkout_experience.selfCheckout.TurnStatement#getDegrees <em>Degrees</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Degrees</em>'.
   * @see self_checkout_experience.selfCheckout.TurnStatement#getDegrees()
   * @see #getTurnStatement()
   * @generated
   */
  EReference getTurnStatement_Degrees();

  /**
   * Returns the meta object for class '{@link self_checkout_experience.selfCheckout.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see self_checkout_experience.selfCheckout.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link self_checkout_experience.selfCheckout.IntLiteral <em>Int Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Literal</em>'.
   * @see self_checkout_experience.selfCheckout.IntLiteral
   * @generated
   */
  EClass getIntLiteral();

  /**
   * Returns the meta object for the attribute '{@link self_checkout_experience.selfCheckout.IntLiteral#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see self_checkout_experience.selfCheckout.IntLiteral#getVal()
   * @see #getIntLiteral()
   * @generated
   */
  EAttribute getIntLiteral_Val();

  /**
   * Returns the meta object for class '{@link self_checkout_experience.selfCheckout.RealLiteral <em>Real Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Real Literal</em>'.
   * @see self_checkout_experience.selfCheckout.RealLiteral
   * @generated
   */
  EClass getRealLiteral();

  /**
   * Returns the meta object for the attribute '{@link self_checkout_experience.selfCheckout.RealLiteral#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see self_checkout_experience.selfCheckout.RealLiteral#getVal()
   * @see #getRealLiteral()
   * @generated
   */
  EAttribute getRealLiteral_Val();

  /**
   * Returns the meta object for class '{@link self_checkout_experience.selfCheckout.IntVarExpression <em>Int Var Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Var Expression</em>'.
   * @see self_checkout_experience.selfCheckout.IntVarExpression
   * @generated
   */
  EClass getIntVarExpression();

  /**
   * Returns the meta object for the reference '{@link self_checkout_experience.selfCheckout.IntVarExpression#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Var</em>'.
   * @see self_checkout_experience.selfCheckout.IntVarExpression#getVar()
   * @see #getIntVarExpression()
   * @generated
   */
  EReference getIntVarExpression_Var();

  /**
   * Returns the meta object for class '{@link self_checkout_experience.selfCheckout.Checkout <em>Checkout</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Checkout</em>'.
   * @see self_checkout_experience.selfCheckout.Checkout
   * @generated
   */
  EClass getCheckout();

  /**
   * Returns the meta object for the containment reference list '{@link self_checkout_experience.selfCheckout.Checkout#getScan <em>Scan</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Scan</em>'.
   * @see self_checkout_experience.selfCheckout.Checkout#getScan()
   * @see #getCheckout()
   * @generated
   */
  EReference getCheckout_Scan();

  /**
   * Returns the meta object for the attribute '{@link self_checkout_experience.selfCheckout.Checkout#getPay <em>Pay</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Pay</em>'.
   * @see self_checkout_experience.selfCheckout.Checkout#getPay()
   * @see #getCheckout()
   * @generated
   */
  EAttribute getCheckout_Pay();

  /**
   * Returns the meta object for class '{@link self_checkout_experience.selfCheckout.Scan <em>Scan</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Scan</em>'.
   * @see self_checkout_experience.selfCheckout.Scan
   * @generated
   */
  EClass getScan();

  /**
   * Returns the meta object for the attribute '{@link self_checkout_experience.selfCheckout.Scan#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see self_checkout_experience.selfCheckout.Scan#getName()
   * @see #getScan()
   * @generated
   */
  EAttribute getScan_Name();

  /**
   * Returns the meta object for the containment reference list '{@link self_checkout_experience.selfCheckout.Scan#getAddToBag <em>Add To Bag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Add To Bag</em>'.
   * @see self_checkout_experience.selfCheckout.Scan#getAddToBag()
   * @see #getScan()
   * @generated
   */
  EReference getScan_AddToBag();

  /**
   * Returns the meta object for class '{@link self_checkout_experience.selfCheckout.AddToBag <em>Add To Bag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Add To Bag</em>'.
   * @see self_checkout_experience.selfCheckout.AddToBag
   * @generated
   */
  EClass getAddToBag();

  /**
   * Returns the meta object for the reference '{@link self_checkout_experience.selfCheckout.AddToBag#getBagItem <em>Bag Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Bag Item</em>'.
   * @see self_checkout_experience.selfCheckout.AddToBag#getBagItem()
   * @see #getAddToBag()
   * @generated
   */
  EReference getAddToBag_BagItem();

  /**
   * Returns the meta object for class '{@link self_checkout_experience.selfCheckout.Addition <em>Addition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Addition</em>'.
   * @see self_checkout_experience.selfCheckout.Addition
   * @generated
   */
  EClass getAddition();

  /**
   * Returns the meta object for the containment reference '{@link self_checkout_experience.selfCheckout.Addition#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see self_checkout_experience.selfCheckout.Addition#getLeft()
   * @see #getAddition()
   * @generated
   */
  EReference getAddition_Left();

  /**
   * Returns the meta object for the attribute list '{@link self_checkout_experience.selfCheckout.Addition#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Operator</em>'.
   * @see self_checkout_experience.selfCheckout.Addition#getOperator()
   * @see #getAddition()
   * @generated
   */
  EAttribute getAddition_Operator();

  /**
   * Returns the meta object for the containment reference list '{@link self_checkout_experience.selfCheckout.Addition#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Right</em>'.
   * @see self_checkout_experience.selfCheckout.Addition#getRight()
   * @see #getAddition()
   * @generated
   */
  EReference getAddition_Right();

  /**
   * Returns the meta object for class '{@link self_checkout_experience.selfCheckout.Multiplication <em>Multiplication</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Multiplication</em>'.
   * @see self_checkout_experience.selfCheckout.Multiplication
   * @generated
   */
  EClass getMultiplication();

  /**
   * Returns the meta object for the containment reference '{@link self_checkout_experience.selfCheckout.Multiplication#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see self_checkout_experience.selfCheckout.Multiplication#getLeft()
   * @see #getMultiplication()
   * @generated
   */
  EReference getMultiplication_Left();

  /**
   * Returns the meta object for the attribute list '{@link self_checkout_experience.selfCheckout.Multiplication#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Operator</em>'.
   * @see self_checkout_experience.selfCheckout.Multiplication#getOperator()
   * @see #getMultiplication()
   * @generated
   */
  EAttribute getMultiplication_Operator();

  /**
   * Returns the meta object for the containment reference list '{@link self_checkout_experience.selfCheckout.Multiplication#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Right</em>'.
   * @see self_checkout_experience.selfCheckout.Multiplication#getRight()
   * @see #getMultiplication()
   * @generated
   */
  EReference getMultiplication_Right();

  /**
   * Returns the meta object for enum '{@link self_checkout_experience.selfCheckout.MoveCommand <em>Move Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Move Command</em>'.
   * @see self_checkout_experience.selfCheckout.MoveCommand
   * @generated
   */
  EEnum getMoveCommand();

  /**
   * Returns the meta object for enum '{@link self_checkout_experience.selfCheckout.TurnCommand <em>Turn Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Turn Command</em>'.
   * @see self_checkout_experience.selfCheckout.TurnCommand
   * @generated
   */
  EEnum getTurnCommand();

  /**
   * Returns the meta object for enum '{@link self_checkout_experience.selfCheckout.Pay <em>Pay</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Pay</em>'.
   * @see self_checkout_experience.selfCheckout.Pay
   * @generated
   */
  EEnum getPay();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SelfCheckoutFactory getSelfCheckoutFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckout.impl.Self_checkoutImpl <em>Self checkout</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckout.impl.Self_checkoutImpl
     * @see self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl#getSelf_checkout()
     * @generated
     */
    EClass SELF_CHECKOUT = eINSTANCE.getSelf_checkout();

    /**
     * The meta object literal for the '<em><b>Pick</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELF_CHECKOUT__PICK = eINSTANCE.getSelf_checkout_Pick();

    /**
     * The meta object literal for the '<em><b>Walkstatements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELF_CHECKOUT__WALKSTATEMENTS = eINSTANCE.getSelf_checkout_Walkstatements();

    /**
     * The meta object literal for the '<em><b>Checkout</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELF_CHECKOUT__CHECKOUT = eINSTANCE.getSelf_checkout_Checkout();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckout.impl.PickImpl <em>Pick</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckout.impl.PickImpl
     * @see self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl#getPick()
     * @generated
     */
    EClass PICK = eINSTANCE.getPick();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PICK__NAME = eINSTANCE.getPick_Name();

    /**
     * The meta object literal for the '<em><b>Holding Item</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PICK__HOLDING_ITEM = eINSTANCE.getPick_HoldingItem();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckout.impl.AddToBasketImpl <em>Add To Basket</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckout.impl.AddToBasketImpl
     * @see self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl#getAddToBasket()
     * @generated
     */
    EClass ADD_TO_BASKET = eINSTANCE.getAddToBasket();

    /**
     * The meta object literal for the '<em><b>Item</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADD_TO_BASKET__ITEM = eINSTANCE.getAddToBasket_Item();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckout.impl.DropImpl <em>Drop</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckout.impl.DropImpl
     * @see self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl#getDrop()
     * @generated
     */
    EClass DROP = eINSTANCE.getDrop();

    /**
     * The meta object literal for the '<em><b>Item</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DROP__ITEM = eINSTANCE.getDrop_Item();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckout.impl.WalkStatementImpl <em>Walk Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckout.impl.WalkStatementImpl
     * @see self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl#getWalkStatement()
     * @generated
     */
    EClass WALK_STATEMENT = eINSTANCE.getWalkStatement();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckout.impl.VariableDeclarationImpl <em>Variable Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckout.impl.VariableDeclarationImpl
     * @see self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl#getVariableDeclaration()
     * @generated
     */
    EClass VARIABLE_DECLARATION = eINSTANCE.getVariableDeclaration();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_DECLARATION__NAME = eINSTANCE.getVariableDeclaration_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_DECLARATION__VALUE = eINSTANCE.getVariableDeclaration_Value();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckout.impl.LoopStatementImpl <em>Loop Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckout.impl.LoopStatementImpl
     * @see self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl#getLoopStatement()
     * @generated
     */
    EClass LOOP_STATEMENT = eINSTANCE.getLoopStatement();

    /**
     * The meta object literal for the '<em><b>Count</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOOP_STATEMENT__COUNT = eINSTANCE.getLoopStatement_Count();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOOP_STATEMENT__STATEMENTS = eINSTANCE.getLoopStatement_Statements();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckout.impl.MoveStatementImpl <em>Move Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckout.impl.MoveStatementImpl
     * @see self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl#getMoveStatement()
     * @generated
     */
    EClass MOVE_STATEMENT = eINSTANCE.getMoveStatement();

    /**
     * The meta object literal for the '<em><b>Command</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOVE_STATEMENT__COMMAND = eINSTANCE.getMoveStatement_Command();

    /**
     * The meta object literal for the '<em><b>Steps</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MOVE_STATEMENT__STEPS = eINSTANCE.getMoveStatement_Steps();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckout.impl.TurnStatementImpl <em>Turn Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckout.impl.TurnStatementImpl
     * @see self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl#getTurnStatement()
     * @generated
     */
    EClass TURN_STATEMENT = eINSTANCE.getTurnStatement();

    /**
     * The meta object literal for the '<em><b>Command</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TURN_STATEMENT__COMMAND = eINSTANCE.getTurnStatement_Command();

    /**
     * The meta object literal for the '<em><b>Degrees</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TURN_STATEMENT__DEGREES = eINSTANCE.getTurnStatement_Degrees();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckout.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckout.impl.ExpressionImpl
     * @see self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckout.impl.IntLiteralImpl <em>Int Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckout.impl.IntLiteralImpl
     * @see self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl#getIntLiteral()
     * @generated
     */
    EClass INT_LITERAL = eINSTANCE.getIntLiteral();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT_LITERAL__VAL = eINSTANCE.getIntLiteral_Val();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckout.impl.RealLiteralImpl <em>Real Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckout.impl.RealLiteralImpl
     * @see self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl#getRealLiteral()
     * @generated
     */
    EClass REAL_LITERAL = eINSTANCE.getRealLiteral();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REAL_LITERAL__VAL = eINSTANCE.getRealLiteral_Val();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckout.impl.IntVarExpressionImpl <em>Int Var Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckout.impl.IntVarExpressionImpl
     * @see self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl#getIntVarExpression()
     * @generated
     */
    EClass INT_VAR_EXPRESSION = eINSTANCE.getIntVarExpression();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INT_VAR_EXPRESSION__VAR = eINSTANCE.getIntVarExpression_Var();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckout.impl.CheckoutImpl <em>Checkout</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckout.impl.CheckoutImpl
     * @see self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl#getCheckout()
     * @generated
     */
    EClass CHECKOUT = eINSTANCE.getCheckout();

    /**
     * The meta object literal for the '<em><b>Scan</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHECKOUT__SCAN = eINSTANCE.getCheckout_Scan();

    /**
     * The meta object literal for the '<em><b>Pay</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHECKOUT__PAY = eINSTANCE.getCheckout_Pay();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckout.impl.ScanImpl <em>Scan</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckout.impl.ScanImpl
     * @see self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl#getScan()
     * @generated
     */
    EClass SCAN = eINSTANCE.getScan();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCAN__NAME = eINSTANCE.getScan_Name();

    /**
     * The meta object literal for the '<em><b>Add To Bag</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCAN__ADD_TO_BAG = eINSTANCE.getScan_AddToBag();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckout.impl.AddToBagImpl <em>Add To Bag</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckout.impl.AddToBagImpl
     * @see self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl#getAddToBag()
     * @generated
     */
    EClass ADD_TO_BAG = eINSTANCE.getAddToBag();

    /**
     * The meta object literal for the '<em><b>Bag Item</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADD_TO_BAG__BAG_ITEM = eINSTANCE.getAddToBag_BagItem();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckout.impl.AdditionImpl <em>Addition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckout.impl.AdditionImpl
     * @see self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl#getAddition()
     * @generated
     */
    EClass ADDITION = eINSTANCE.getAddition();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADDITION__LEFT = eINSTANCE.getAddition_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ADDITION__OPERATOR = eINSTANCE.getAddition_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADDITION__RIGHT = eINSTANCE.getAddition_Right();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckout.impl.MultiplicationImpl <em>Multiplication</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckout.impl.MultiplicationImpl
     * @see self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl#getMultiplication()
     * @generated
     */
    EClass MULTIPLICATION = eINSTANCE.getMultiplication();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTIPLICATION__LEFT = eINSTANCE.getMultiplication_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MULTIPLICATION__OPERATOR = eINSTANCE.getMultiplication_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTIPLICATION__RIGHT = eINSTANCE.getMultiplication_Right();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckout.MoveCommand <em>Move Command</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckout.MoveCommand
     * @see self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl#getMoveCommand()
     * @generated
     */
    EEnum MOVE_COMMAND = eINSTANCE.getMoveCommand();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckout.TurnCommand <em>Turn Command</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckout.TurnCommand
     * @see self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl#getTurnCommand()
     * @generated
     */
    EEnum TURN_COMMAND = eINSTANCE.getTurnCommand();

    /**
     * The meta object literal for the '{@link self_checkout_experience.selfCheckout.Pay <em>Pay</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see self_checkout_experience.selfCheckout.Pay
     * @see self_checkout_experience.selfCheckout.impl.SelfCheckoutPackageImpl#getPay()
     * @generated
     */
    EEnum PAY = eINSTANCE.getPay();

  }

} //SelfCheckoutPackage
