/**
 * generated by Xtext 2.25.0
 */
package self_checkout_experience.selfCheckout;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Walk Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see self_checkout_experience.selfCheckout.SelfCheckoutPackage#getWalkStatement()
 * @model
 * @generated
 */
public interface WalkStatement extends EObject
{
} // WalkStatement
